from __future__ import annotations

from datetime import datetime, UTC
from html import escape
from math import cos, pi, sin
from pathlib import Path


def polar(cx: float, cy: float, radius: float, angle_deg: float) -> tuple[float, float]:
    angle = pi * angle_deg / 180
    return cx + radius * cos(angle), cy + radius * sin(angle)


def main() -> None:
    width, height = 1200, 760
    cx, cy = 430, 380
    rings = [110, 180, 250]
    label_radius = rings[-1] + 30
    chart_translate_y = 20
    labels = [
        ("Environmental Compliance", 96),
        ("Python Web Apps", 18),
        ("Database Work", 72),
        ("GIS Mapping", 82),
        ("WordPress & Web Design", 84),
        ("Hardware Troubleshooting", 78),
        ("Graphics & Audio", 75),
        ("Documentation", 93),
    ]
    start_angle = -90
    step = 360 / len(labels)

    chart_points = []
    node_markup = []
    axis_markup = []
    label_markup = []

    for i, (name, score) in enumerate(labels):
        safe_name = escape(name)
        angle = start_angle + i * step
        outer_x, outer_y = polar(cx, cy, rings[-1], angle)
        data_x, data_y = polar(cx, cy, rings[-1] * (score / 100), angle)
        text_x, text_y = polar(cx, cy, label_radius, angle)

        chart_points.append(f"{data_x:.2f},{data_y:.2f}")
        axis_markup.append(
            f'<line x1="{cx}" y1="{cy}" x2="{outer_x:.2f}" y2="{outer_y:.2f}" '
            'stroke="rgba(33,40,50,.22)" stroke-width="1.5" />'
        )
        node_markup.append(
            f'<circle cx="{data_x:.2f}" cy="{data_y:.2f}" r="6.5" fill="#1e6aa8" />'
        )
        label_anchor = "middle"
        if text_x < cx - 10:
            label_anchor = "end"
        elif text_x > cx + 10:
            label_anchor = "start"
        label_markup.append(
            f'<text x="{text_x:.2f}" y="{text_y:.2f}" text-anchor="{label_anchor}" '
            'font-size="18" font-weight="700" fill="#000c2d">'
            f"{safe_name}</text>"
        )
        label_markup.append(
            f'<text x="{text_x:.2f}" y="{text_y + 22:.2f}" text-anchor="{label_anchor}" '
            'font-size="14" fill="#687385">'
            f"Level: {score}/100</text>"
        )

    rings_markup = []
    ring_labels = ["Foundational", "Strong", "Expert"]
    for i, radius in enumerate(rings):
        rings_markup.append(
            f'<circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" '
            'stroke="rgba(0,12,45,.16)" stroke-width="1.4" />'
        )
        rings_markup.append(
            f'<text x="{cx + radius + 10}" y="{cy - 6}" font-size="12" fill="#687385">{ring_labels[i]}</text>'
        )

    now = datetime.now(UTC).strftime("%Y-%m-%d UTC")
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
  <title id="title">Python-Generated Skill Map</title>
  <desc id="desc">Static radar-style map generated by Python for portfolio use.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#f7f9fc" />
      <stop offset="100%" stop-color="#eef2f6" />
    </linearGradient>
    <linearGradient id="poly" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1e6aa8" stop-opacity=".42" />
      <stop offset="100%" stop-color="#2c5f8f" stop-opacity=".50" />
    </linearGradient>
  </defs>

  <rect x="0" y="0" width="{width}" height="{height}" fill="url(#bg)" />
  <rect x="24" y="24" width="{width - 48}" height="{height - 48}" rx="22" fill="#ffffff" fill-opacity=".78" stroke="rgba(0,12,45,.12)" />

  <text x="74" y="88" font-size="40" font-family="Inter, Arial, sans-serif" font-weight="700" fill="#000c2d">
    Ronaldo Ballecer Skill Map
  </text>
  <text x="74" y="118" font-size="18" font-family="Inter, Arial, sans-serif" fill="#687385">
    Generated with Python
  </text>

  <g transform="translate(0 {chart_translate_y})">
    {''.join(rings_markup)}
    {''.join(axis_markup)}
    <polygon points="{' '.join(chart_points)}" fill="url(#poly)" stroke="#000c2d" stroke-width="2.2" />
    {''.join(node_markup)}
    {''.join(label_markup)}
    <circle cx="{cx}" cy="{cy}" r="8" fill="#000c2d" />
  </g>

  <g>
    <rect x="760" y="220" width="350" height="220" rx="16" fill="#ffffff" fill-opacity=".84" stroke="rgba(0,12,45,.10)" />
    <text x="786" y="260" font-size="24" font-weight="700" fill="#000c2d">How To Update</text>
    <text x="786" y="292" font-size="16" fill="#687385">1. Edit scores in generate_skill_map.py</text>
    <text x="786" y="322" font-size="16" fill="#687385">2. Run: python generate_skill_map.py</text>
    <text x="786" y="352" font-size="16" fill="#687385">3. Refresh index.html</text>
    <text x="786" y="396" font-size="14" fill="#687385">Last generated: {now}</text>
  </g>
</svg>
"""

    out_dir = Path("assets")
    out_dir.mkdir(exist_ok=True)
    (out_dir / "python_skill_map.svg").write_text(svg, encoding="utf-8")
    print("Generated assets/python_skill_map.svg")


if __name__ == "__main__":
    main()
